application: yohackernews
version: 1
runtime: python
api_version: 1 

handlers:
- url: /files
  static_dir: media

- url: /favicon\.ico
  static_files: media/img/logo.png
  upload: media/img/logo\.png

- url: /.*
  script: main.py

